markdown: rdiscount
pygments: true
permalink: /:title
auto: true
rdiscount:
  extensions: [smart]
title : 100 Fish Recipes
production_url : http://100fishrecipes.info
description: "100 fish recipes."
author :
  name : Matthew Phillips
